### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by richelbilderbeek**
A simple pull request: I just documented what the name of the arguments mean, to show the workflow

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
@rsetienne : do not forget to accept or reject this Pull Request :-)

**Comment by rsetienne** [comment]
There is already documentation.

**Comment by richelbilderbeek** [comment]
Yes, but not in the code. There should also be comments in the code [1-5].

## References
[1] Google's R Style Guide: Comment your code
[2] Google's R Style Guide: Functions should contain a comments
section immediately below the function definition line. These comments
should consist of a one-sentence description of the function; a list
of the function's arguments, denoted by Args:, with a description of
each (including the data type); and a description of the return value,
denoted by Returns:. The comments should be descriptive enough that a
caller can use the function without reading any of the function's code.
[3] The GNU coding standards, by Free Software Foundation, Inc.,
http://www.gnu.org/prep/standards, Please put a comment on each
function saying what the function does, what sorts of arguments it
gets, and what the possible values of arguments mean and are used for.
[...] Also explain the significance of the return value, if there is one.
[4] Bjarne Stroustrup. Programming. 2009. ISBN: 978-0-321-54372-1.
Chapter 5.9.1: 'Comment your code well'
[5] John Lakos. Large-Scale C++ Software Design. 1996. ISBN:
0-201-63362-0. Chapter 2.6: Document the interfaces so that they are
usable by others. Have at least one other developer review each interface

**Comment by rsetienne** [comment]
I will take a note of that for new code. Simply no time to do this for existing code :-(.
Also, I don't know how to accept or reject pull requests. It's not obvious.

**Comment by rsetienne** [comment]
If you want to add the documentation in the same format as the other R functions, be my guest :-).

**Comment by richelbilderbeek** [comment]
I'll try to be a good boy :-)

**Comment by rsetienne** [comment]
OK. Thanks.

**Pull request closed without merging**
